### ISSUE TITLE
linchpin rise seems to be unable to find the linchpin_config and fails with Unicode parse error

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#135]
$ linchpin rise
debug:: current working directory
/home/herlo/Projects/lpdemo
debug:: c_file
/home/herlo/Projects/lpdemo/linchpin_config.yml
debug:: c_file
/home/herlo/Projects/lpdemo/linch-pin/linchpin_config.yml
debug:: c_file
~/.linchpin_config.yml
debug:: c_file
/home/herlo/.virtualenvs/venv3/lib/python2.7/site-packages/linchpin_config.yml
debug:: c_file
/etc/linchpin_config.yml
debug:: current working directory
/home/herlo/Projects/lpdemo
debug:: c_file
/home/herlo/Projects/lpdemo/linchpin_config.yml
debug:: c_file
/home/herlo/Projects/lpdemo/linch-pin/linchpin_config.yml
debug:: c_file
~/.linchpin_config.yml
debug:: c_file
/home/herlo/.virtualenvs/venv3/lib/python2.7/site-packages/linchpin_config.yml
debug:: c_file
/etc/linchpin_config.yml
debug:: config_path
None
debug::print file path
None
Traceback (most recent call last):
  File "/home/herlo/.virtualenvs/venv3/bin/linchpin", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/herlo/.virtualenvs/venv3/lib/python2.7/site-packages/linchpin.py", line 191, in rise
    output = lpcli.lp_rise(pf, target)
  File "/home/herlo/.virtualenvs/venv3/lib/python2.7/site-packages/cli/cli.py", line 86, in lp_rise
    pf)
  File "/home/herlo/.virtualenvs/venv3/lib/python2.7/site-packages/cli/cli.py", line 22, in find_topology
    config = self.get_config()
  File "/home/herlo/.virtualenvs/venv3/lib/python2.7/site-packages/linchpin_api/v1/api.py", line 58, in get_config
    config = parse_yaml(config_path)
  File "/home/herlo/.virtualenvs/venv3/lib/python2.7/site-packages/linchpin_api/v1/utils.py", line 31, in parse_yaml
    with open(pf, 'r') as stream:
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by samvarankashyap** [comment]
@herlo PR #136  fixes  the Issue
