### ISSUE TITLE
Fresh Install fails with errors

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linch-pin#190]
A fresh install of the git master branch (but not the released tarball) fails to execute commands with the following error:

```
$ linchpin init
Traceback (most recent call last):
  File "/home/fedora/venv/test/bin/linchpin", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/fedora/venv/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/home/fedora/venv/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/home/fedora/venv/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/fedora/venv/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/fedora/venv/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/fedora/venv/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.13.0 (/home/fedora/venv/test/lib/python2.7/site-packages), Requirement.parse('requests!=2.12.2,!=2.13.0,>=2.10.0'), set(['keystoneauth1', 'python-cinderclient']))```

**Comment by robled** [comment]
FWIW, I found that manually installing requests 2.10.0 will resolve the version conflict.
