### ISSUE TITLE
"develop" branch fails to execute

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linch-pin#200]
Trying both a `linchpin rise` and a `linchpin validate ...` command from the current (Apr 5) head of the "develop" branch results in the following stack trace:
```
$ linchpin validate topology topologies/openshift_pod.yml
inside validate topology
Traceback (most recent call last):
  File "/home/fedora/venv/linchpin/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin', 'console_scripts', 'linchpin')()
  File "/home/fedora/venv/linchpin/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/fedora/venv/linchpin/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/fedora/venv/linchpin/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fedora/venv/linchpin/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fedora/venv/linchpin/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fedora/venv/linchpin/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/fedora/venv/linchpin/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/fedora/venv/linchpin/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/fedora/linchpin/linchpin/__init__.py", line 261, in validate_topology
    lpcli = LinchpinCli(context)
TypeError: __init__() takes exactly 1 argument (2 given)
```

Other notes:
Installed directly from source with `pip install -e .`
Checkout directory is `/home/fedora/linchpin` per the stacktrace above
Tried both with my existing config directory and a newly configured directory with bare minimal `linchpin init` output in it.

**Comment by samvarankashyap** [comment]
@herlo : found the source of bug . The linchpin/cli/__init__.py was not updated during the recent PR . 
the file is supposed to look as follows:
```python
import os
import click
from linchpin.api import LinchpinAPI
from linchpin.api.invoke_playbooks import invoke_linchpin
from utils import parse_yaml


class LinchpinCli(LinchpinAPI):

    def __init__(self, context):
        LinchpinAPI.__init__(self, context)

    def test(self):
        print("test function inside linchpincli")
```
